site_name: "SSG Playground"
repo_url: https://github.com/tri-star/ssg-playground
edit_uri: edit/master/mkdocs/docs
theme:
  name: 'material'
#  custom_dir: overrides
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo

use_directory_urls: false

extra_css:
  - custom.css

nav:
  - 'Top': '/'
  - './markdown.md'
  - 'Vue':
    - 'Top': './vue/index.md'
    - './vue/install.md'
    - './vue/basic.md'
    - './vue/component.md'
    - './vue/transition.md'
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - toc:
      permalink: true
